Spring:
  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:mysql://localhost:3306/ktems
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 4000
  error:
    include-message: always


app:
  jwtSecret: BAvl5GWxoeZRkbsqM244PpfUWU8UuCWQstBiO9fLRcJmgimSesfpVnkpMF62C5w
  jwtExpirationInMs: 86400000 # 24 hrs